version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: vegapunk-benchmark-postgres
    environment:
      POSTGRES_DB: cineminha_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    networks:
      - benchmark-net

volumes:
  pgdata:

networks:
  benchmark-net:
    driver: bridge
